# Generated by Django 5.1.3 on 2024-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deaprtment', models.CharField(max_length=255)),
                ('mark', models.IntegerField(max_length=3)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
